version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
      args:
        JAR_FILE: build/libs/*.jar
    image: soulplay95/rnb_backend:latest
    ports:
      - '8082:8080'
    container_name: backend_blue
