# FROM openjdk:11
# WORKDIR /usr/src/app
# RUN echo "PWD is: $PWD"
# COPY ./build/*.jar backend.jar
# ENTRYPOINT ["java","-jar","-Dserver.port=8080","backend.jar"]

FROM openjdk:11 AS builder
WORKDIR /app/backend
COPY . .
RUN chmod +x ./gradlew

RUN rm -rf src/test
RUN ./gradlew clean build

FROM adoptopenjdk:11-jdk
COPY --from=builder /app/backend/build/libs/*.jar /

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/0.0.1-SNAPSHOT.jar"]