version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:80
    networks:
      - rnb
    restart: always
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 8080:8080
    networks:
      - rnb
    restart: always
  # jenkins:
  #   container_name: jenkins
  #   image: jenkins/jenkins
  #   ports:
  #     - 7777:8080
  #     - 50000:50000
  #   volumes:
  #     - /var/jenkins_home:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
  #   restart: unless-stopped
networks:
  rnb:
